### ISSUE TITLE
patch方式配置文件写法

### ISSUE THREAD

**Issue by raawaa** [rtransformation/rime-opencc_emoji_symbols#6]
如果是使用custom文件patch的方式配置可以这么写，在这里贴出来看看有没有参考价值。

```yaml

patch:
  switches/@next:
    name: show_es
    reset: 1
    states: [ 😔, 😀 ]
  'engine/filters/@before 0':
    simplifier@es_conversion
  es_conversion:
    opencc_config: es.json
    option_name: show_es
    tips: all

```
