### ISSUE TITLE
部分emoji无法打出来

### ISSUE THREAD

**Issue by raawaa** [rtransformation/rime-opencc_emoji_symbols#7]
使用中发现，有部分emoji打不出来。

比如打「六十四卦」可以正常打出emoji
![image](https://user-images.githubusercontent.com/8319722/112691700-a77c4d00-8eb8-11eb-822a-9217315cfc5e.png)

但是打「数字」就打不出来
![image](https://user-images.githubusercontent.com/8319722/112691735-b7942c80-8eb8-11eb-97bb-2196805d8790.png)

对照`es.txt`里的定义测试了几个，发现打不出来的还不少。

**Comment by raawaa** [comment]
自己找到了问题的根源，`engine/filters`设置的顺序很有讲究，`simplifier@es_conversion`必须放在`simplifier`的后面：

```yaml
engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - reverse_lookup_translator
    - script_translator
  filters:
    - simplifier
    - simplifier@es_conversion  # 必须放在 simplifier 的后面
    - uniquifier
 ```

如果是用patch的方法配置的话，可以这么写：

```yaml
patch:
  switches/@next:
    name: show_es
    reset: 1
    states: [ 😔, 😀 ]
  'engine/filters/@before 1': # 定位patch位置
    simplifier@es_conversion
  es_conversion:
    opencc_config: es.json
    option_name: show_es
    tips: all
```
